version: '3'
services:  
  nginx:
    image: nginx:alpine
    container_name: nginx_react
    volumes:
      - ./config/:/etc/nginx/conf.d
      - ./build:/var/www/html/
    ports:
      - "80:80"
    restart: always